import groovy.transform.Field

// We need this because of the mono repo :(
@Field String PROJECT_DIR = 'rusty-report-printer'

pipeline {
    agent {
        kubernetes {
            inheritFrom 'Node18Alpine Kaniko'
            yamlMergeStrategy merge()
            defaultContainer 'rust'
            yaml '''
              spec:
                containers:
                  - name: rust
                    image: rustlang/rust:nightly-alpine
                    command: ["sleep", "infinity"]
                    resources:
                      requests:
                        cpu: 100m
                        memory: 256Mi
                      limits:
                        cpu: 2
                        memory: 256Mi
            '''
        }
    }

    environment {
        CARGO_UNSTABLE_SPARSE_REGISTRY = 'true'
    }

    options {
        buildDiscarder logRotator(numToKeepStr: '10')
        disableConcurrentBuilds()
        timeout(time: 10, unit: 'MINUTES')
        ansiColor('xterm')
    }

    stages {
        stage('Generate Report') {
            steps {
                dir(PROJECT_DIR) {
                    container('node18') {
                        sh './report_generator.js'
                    }
                }
            }
        }

        stage('Install dependencies') {
            steps {
                dir(PROJECT_DIR) {
                    // if we are on alpine, we need to install musl-dev
                    sh 'apk add --no-cache musl-dev=1.2.2-r7'
                }
            }
        }


        stage('Build') {
            steps {
                dir(PROJECT_DIR) {
                    sh 'cargo build --locked'
                }
            }
        }

        stage('Build Image') {
            steps {
                script {
                    kaniko.buildNoPush(
                            imageName: 'rusty-report-printer',
                            imageTag: getImageTags(),
                            context: PROJECT_DIR,
                            dockerfile: './Dockerfile',
                            extraArgs: '--use-new-run --snapshotMode=redo'
                    )
                }
            }
        }
    }
}

def getImageTags() {
    def commitTag = sanitizeImageTag("${env.GIT_BRANCH}-${env.GIT_COMMIT}")
    def tags = [commitTag]

    if (isMaster()) {
        tags += 'latest'
    }

    return tags
}
